### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingadb-web#167]
- [x] Badge hover styles
- [x] ~Controls baseline~ #185 
- [x] ~Perfdata chart styles~ #160 
- [x] Ellipsize search bar https://github.com/Icinga/ipl-web/commit/1abf667ceb2866c4734ab1b76a0814f22ffc0de6
- [x] ~Downtime detail area~ #193
- [x] List items in detail areas shouldn't be clickable
- [x] Host detail area total services hover style missing bottom padding
- [x] Service shouldn't be clickable in the service detail area's list item
- [x] Host shouldn't be clickable in the host detail area's list item
- [x] Don't show object links in downtimes and comments in the host and service detail areas
- [x] User group badges icon margin/padding
- [x] ~Newlines in comments and downtimes~ #165 
- [x] ~Downtime detail area box sizing and overflow~ #44
- [x] Design comment detail area (watch out for Markdown) and also adjust comment styles in the downtime detail area
- [x] Add "Users" heading in the user group detail area
- [x] ~Show user and user group custom vars in the respective detail areas~ #19
- [x] ~History detail areas missing~ #188
- [x] ~Show address in host detail area and name if different to display name~ #55

**Comment by flourish86** [comment]
I'd add this:

- [ ]  decrease icon sizes in state balls for minimal view mode lists, see

![Screen Shot 2021-04-12 at 17 11 09](https://user-images.githubusercontent.com/6977434/114417908-4e97fe80-9bb2-11eb-9e06-199763affbe2.png)

**Comment by flourish86** [comment]
> Downtime detail area

Not sure, what's meant there. @lippserd create the ticket.

But from what I see on first sight it's the header (padding-bottom to the list item) and the comment area, which are odd.

![Screen Shot 2021-04-26 at 14 49 17](https://user-images.githubusercontent.com/6977434/116084940-96cd1b80-a69e-11eb-9879-c2f2a264fc50.png)

> User group badges icon margin/padding

The hover state is missing a bottom padding. This is again, something that was already fine at some point but broke on the way.

![Screen Shot 2021-04-26 at 14 51 43](https://user-images.githubusercontent.com/6977434/116085337-04794780-a69f-11eb-903b-ba88057873fa.png)

**Comment by nilmerg** [comment]
> > Downtime detail area
> 
> But from what I see on first sight it's the header (padding-bottom to the list item) and the comment area, which are odd.

Seems to be a browser issue. Looks fine in Chrome.

![Screenshot from 2021-04-26 14-56-11](https://user-images.githubusercontent.com/16668527/116085975-a7ca5c80-a69f-11eb-92d5-deed597b98fb.png)

> > User group badges icon margin/padding
> 
> The hover state is missing a bottom padding. This is again, something that was already fine at some point but broke on the way.

There's a specific point about that. My question was regarding the **user group** badges..

**Comment by nilmerg** [comment]
> Seems to be a browser issue. Looks fine in Chrome.

Nevermind, accidentally fixed that as part of #113 and #93.

**Comment by flourish86** [comment]
> > > User group badges icon margin/padding
> > 
> > 
> > The hover state is missing a bottom padding. This is again, something that was already fine at some point but broke on the way.
> 
> There's a specific point about that. My question was regarding the **user group** badges..

I don't see any problems with those.

Just to be sure, we're talking the same or rather see the same:

![Screen Shot 2021-04-26 at 15 26 41](https://user-images.githubusercontent.com/6977434/116090127-d5190980-a6a3-11eb-80b6-72aff1899fa3.png)

**Comment by nilmerg** [comment]
Well, yes, see my screenshot :joy:

**Comment by flourish86** [comment]
> Well, yes, see my screenshot 😂

Mine was about the hover not the content.

**Comment by nilmerg** [comment]
And Eric's about margin/padding.

**Comment by nilmerg** [comment]
I've adjusted the markdown formatting. Though, didn't change anything else in the comment detail section. Don't know what I should do there, maybe showing the remove button in the upper right?

Comments without any markdown are still pretty boring, though since there's no way to distinguish between markdown and non-markdown, I don't see how I could improve this.

![Screenshot from 2021-04-27 13-41-00](https://user-images.githubusercontent.com/16668527/116235554-4ae1ab80-a75e-11eb-818d-d680e198b873.png)
![Screenshot from 2021-04-27 13-41-19](https://user-images.githubusercontent.com/16668527/116235550-4a491500-a75e-11eb-9268-01e005b811cb.png)

**Comment by flourish86** [comment]
> I've adjusted the markdown formatting. Though, didn't change anything else in the comment detail section. Don't know what I should do there, maybe showing the remove button in the upper right?
> 
> Comments without any markdown are still pretty boring, though since there's no way to distinguish between markdown and non-markdown, I don't see how I could improve this.
> 
> ![Screenshot from 2021-04-27 13-41-00](https://user-images.githubusercontent.com/16668527/116235554-4ae1ab80-a75e-11eb-818d-d680e198b873.png) ![Screenshot from 2021-04-27 13-41-19](https://user-images.githubusercontent.com/16668527/116235550-4a491500-a75e-11eb-9268-01e005b811cb.png)

We should display the comment content, be it markdown or not, differently. Currently the content blend in with the detail area structure (headlines, etc.).

This is much clearer:

![Screen Shot 2021-04-28 at 13 22 35](https://user-images.githubusercontent.com/6977434/116395945-09680380-a825-11eb-8d1d-16fc3a2fdc89.png)

The headline "Comment" can be removed since it's self-explanatory.

I'd also consider having the content collapsible to keep the rest of the page in reach, when there's a loooooong comment. For comments this could be solved by moving the destructive action to the controls (which I wouldn't suggest, but also not strongly oppose).

Downtime detail has additional content below the comment, though. So having a long content could push these elements out of sight.

**Comment by flourish86** [comment]
> Comments without any markdown are still pretty boring, though since there's no way to distinguish between markdown and non-markdown, I don't see how I could improve this.

I don't see, why we had to distinguish. For the user it does not matter.

Look at this view at GitHub here, where markdown is also supported. Have you ever wondered, if the comments you read was intended to be in markdown or not? Let's keep it simple.

**Comment by nilmerg** [comment]
The user doesn't care from the technical perspective, but doesn't it look weird if the entire comment has a non-standard background and then code or quotes in markdown also have one?

**Comment by flourish86** [comment]
> The user doesn't care from the technical perspective, but doesn't it look weird if the entire comment has a non-standard background and then code or quotes in markdown also have one?

Can't we decide ourselves, how this all is going to look?

**Comment by nilmerg** [comment]
Then make a suggestion, how code and quotes should look like?

**Comment by nilmerg** [comment]
> The headline "Comment" can be removed since it's self-explanatory.

Really? Sure, the comment in the picture is useless, but we can't be sure every comment is *self-explanatory*. Also, the downtime detail shows the title to differentiate it from the other sections, why should the comment detail be different here? It's even more of a consistency issue since any other detail view also has a title at the very top.

![Screenshot from 2021-04-29 08-19-58](https://user-images.githubusercontent.com/16668527/116509928-66ff5d00-a8c4-11eb-8ba5-2a545e48c09f.png)

> We should display the comment content, be it markdown or not, different to the structure. Currently the content blend in with the detail area structure (headlines, etc.).

Gave the comment now the same background, padding and rounded-borders as for plugin output. Though, especially on large comments this looks too prominent to me. I'd rather not have a background there, to be honest.

![Screenshot from 2021-04-29 08-20-28](https://user-images.githubusercontent.com/16668527/116509593-e2acda00-a8c3-11eb-9a95-d944978f44a9.png)![Screenshot from 2021-04-29 08-20-40](https://user-images.githubusercontent.com/16668527/116509590-e17bad00-a8c3-11eb-8a2d-d5926dc139e5.png)

**Comment by nilmerg** [comment]
Fixed most issues mentioned in the OP and more. Opened or referenced issues for all issues I didn't fix. Closing this then. For future problems please open separate issues.
